name: build-test-action
run-name: Build and test validation for repo

on: 
    push:
    pull_request:
        branches: [ main ]
    
jobs:
  build-test-validation:

    name: build-test-validation-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Display dotnet version
      run: dotnet --version

    - name: Install Dependencies
      run: dotnet restore

    - name: Run Build Validation
      run: dotnet build

      # working on test validation